-- Built-in defaults and singleton state.

INSERT INTO public.policy_groups (id, name, enabled, selector_expression, notes, created_by, updated_by, created_at, updated_at) VALUES ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa3', 'Predefined traffic quota warning', false, 'status:online', 'Disabled predefined policy. Enable or edit after configuring VPS traffic quota rules.', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_groups (id, name, enabled, selector_expression, notes, created_by, updated_by, created_at, updated_at) VALUES ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa4', 'Predefined CPU utilization', false, 'status:online', 'Disabled predefined policy. Enable or edit after confirming fleet-specific CPU utilization expectations.', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_groups (id, name, enabled, selector_expression, notes, created_by, updated_by, created_at, updated_at) VALUES ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa5', 'Predefined memory availability', false, 'status:online', 'Disabled predefined policy. Enable or edit after confirming fleet-specific memory availability thresholds.', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_groups (id, name, enabled, selector_expression, notes, created_by, updated_by, created_at, updated_at) VALUES ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa6', 'Predefined disk availability', false, 'status:online', 'Disabled predefined policy. Enable or edit after confirming fleet-specific disk availability thresholds.', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_groups (id, name, enabled, selector_expression, notes, created_by, updated_by, created_at, updated_at) VALUES ('c1000000-0000-4000-8000-000000000001', 'System operational evidence policies', true, '*', 'Enabled deterministic defaults for normalized operational evidence. Operators may edit or disable these built-in policies.', NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb3', 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa3', 1, 0, 'Traffic cycle above 80%', true, NULL, 'traffic.cycle_percent >= 80', 'warning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'metric', 'telemetry.combined', 'natural_key', 'traffic', 'Traffic quota threshold reached', '{subject.display_name} matched policy condition {policy_rule.trigger_condition_expression}', '{"kind": "sustained", "seconds": 300}', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb4', 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa4', 1, 0, 'CPU utilization from 75% to 90%', true, NULL, 'cpu.utilization_ratio >= 0.75 && cpu.utilization_ratio < 0.90', 'warning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'metric', 'telemetry.combined', 'natural_key', 'resource', 'Resource policy threshold reached', '{subject.display_name} matched policy condition {policy_rule.trigger_condition_expression}', '{"kind": "sustained", "seconds": 300}', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb5', 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa4', 1, 1, 'CPU utilization at or above 90%', true, NULL, 'cpu.utilization_ratio >= 0.90', 'critical', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'metric', 'telemetry.combined', 'natural_key', 'resource', 'Resource policy threshold reached', '{subject.display_name} matched policy condition {policy_rule.trigger_condition_expression}', '{"kind": "sustained", "seconds": 300}', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb6', 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa5', 1, 0, 'Available memory from 10% to 20%', true, NULL, 'memory.available_ratio <= 0.20 && memory.available_ratio > 0.10', 'warning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'metric', 'telemetry.combined', 'natural_key', 'resource', 'Resource policy threshold reached', '{subject.display_name} matched policy condition {policy_rule.trigger_condition_expression}', '{"kind": "sustained", "seconds": 300}', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb7', 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa5', 1, 1, 'Available memory at or below 10%', true, NULL, 'memory.available_ratio <= 0.10', 'critical', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'metric', 'telemetry.combined', 'natural_key', 'resource', 'Resource policy threshold reached', '{subject.display_name} matched policy condition {policy_rule.trigger_condition_expression}', '{"kind": "sustained", "seconds": 300}', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb8', 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa6', 1, 0, 'Available disk from 10% to 20%', true, NULL, 'disk.available_ratio <= 0.20 && disk.available_ratio > 0.10', 'warning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'metric', 'telemetry.combined', 'natural_key', 'resource', 'Resource policy threshold reached', '{subject.display_name} matched policy condition {policy_rule.trigger_condition_expression}', '{"kind": "sustained", "seconds": 300}', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb9', 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa6', 1, 1, 'Available disk at or below 10%', true, NULL, 'disk.available_ratio <= 0.10', 'critical', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'metric', 'telemetry.combined', 'natural_key', 'resource', 'Resource policy threshold reached', '{subject.display_name} matched policy condition {policy_rule.trigger_condition_expression}', '{"kind": "sustained", "seconds": 300}', NULL, NULL, NULL, 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('d1000000-0000-4000-8000-000000000001', 'c1000000-0000-4000-8000-000000000001', 1, 0, 'Agent never connected', true, NULL, 'evidence.status = never', 'warning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'state', 'agent.status', 'natural_key', 'agent_status', 'Agent is not online', '{subject.display_name} currently reports {evidence.status}', '{"kind": "sustained", "seconds": 600}', NULL, '{"kind": "sustained", "seconds": 60}', 'agent.never_connected', 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('d1000000-0000-4000-8000-000000000002', 'c1000000-0000-4000-8000-000000000001', 1, 1, 'Agent connectivity degraded', true, NULL, 'evidence.status in [disconnected, stale]', 'warning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'state', 'agent.status', 'natural_key', 'agent_status', 'Agent is not online', '{subject.display_name} currently reports {evidence.status}', '{"kind": "sustained", "seconds": 120}', NULL, '{"kind": "sustained", "seconds": 60}', 'agent.connectivity_degraded', 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('d1000000-0000-4000-8000-000000000003', 'c1000000-0000-4000-8000-000000000001', 1, 2, 'Agent offline', true, NULL, 'evidence.status = offline', 'critical', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'state', 'agent.status', 'natural_key', 'agent_status', 'Agent is not online', '{subject.display_name} currently reports {evidence.status}', '{"kind": "sustained", "seconds": 120}', NULL, '{"kind": "sustained", "seconds": 60}', 'agent.offline', 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('d1000000-0000-4000-8000-000000000004', 'c1000000-0000-4000-8000-000000000001', 1, 3, 'Agent access revoked', true, NULL, 'evidence.status = revoked', 'critical', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'state', 'agent.access', 'natural_key', 'agent_status', 'VPS access revoked', '{subject.display_name} cannot reconnect until an operator assigns a new key', NULL, NULL, NULL, 'agent.access_revoked', 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('d1000000-0000-4000-8000-000000000005', 'c1000000-0000-4000-8000-000000000001', 1, 4, 'Tunnel adapter failure', true, NULL, 'evidence.adapter.success = false', 'critical', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'state', 'tunnel.adapter', 'natural_key', 'network', 'Tunnel adapter status failed', '{evidence.reason}', '{"kind": "sustained", "seconds": 120}', NULL, '{"kind": "sustained", "seconds": 60}', 'tunnel.adapter_failure', 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('d1000000-0000-4000-8000-000000000006', 'c1000000-0000-4000-8000-000000000001', 1, 5, 'Tunnel traffic degraded', true, NULL, 'evidence.traffic.status != ok', 'warning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'state', 'tunnel.traffic', 'natural_key', 'network', 'Tunnel interface counters are degraded', '{evidence.reason}', '{"kind": "sustained", "seconds": 120}', NULL, '{"kind": "sustained", "seconds": 60}', 'tunnel.traffic_degraded', 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('d1000000-0000-4000-8000-000000000007', 'c1000000-0000-4000-8000-000000000001', 1, 6, 'General job partial success', true, NULL, 'evidence.status = partial_success && !(evidence.command_type in ["*backup*", "*restore*", "*agent_update*"])', 'warning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'occurrence', 'job.terminal', 'natural_key', 'job', 'Job requires operator attention', '{evidence.command_type} job {evidence.status}', NULL, NULL, '{"kind": "elapsed_since_trigger", "seconds": 604800}', 'job.general_partial_success', 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('d1000000-0000-4000-8000-000000000008', 'c1000000-0000-4000-8000-000000000001', 1, 7, 'General job hard failure', true, NULL, 'evidence.status in [canceled, rejected, failed, agent_timeout, control_timeout] && !(evidence.command_type in ["*backup*", "*restore*", "*agent_update*"])', 'critical', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'occurrence', 'job.terminal', 'natural_key', 'job', 'Job requires operator attention', '{evidence.command_type} job {evidence.status}', NULL, NULL, '{"kind": "elapsed_since_trigger", "seconds": 604800}', 'job.general_hard_failure', 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('d1000000-0000-4000-8000-000000000009', 'c1000000-0000-4000-8000-000000000001', 1, 8, 'Backup job partial success', true, NULL, 'evidence.status = partial_success && evidence.command_type in ["*backup*", "*restore*"]', 'warning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'occurrence', 'job.terminal', 'natural_key', 'backup', 'Job requires operator attention', '{evidence.command_type} job {evidence.status}', NULL, NULL, '{"kind": "elapsed_since_trigger", "seconds": 604800}', 'job.backup_partial_success', 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('d1000000-0000-4000-8000-000000000010', 'c1000000-0000-4000-8000-000000000001', 1, 9, 'Backup job hard failure', true, NULL, 'evidence.status in [canceled, rejected, failed, agent_timeout, control_timeout] && evidence.command_type in ["*backup*", "*restore*"]', 'critical', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'occurrence', 'job.terminal', 'natural_key', 'backup', 'Job requires operator attention', '{evidence.command_type} job {evidence.status}', NULL, NULL, '{"kind": "elapsed_since_trigger", "seconds": 604800}', 'job.backup_hard_failure', 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('d1000000-0000-4000-8000-000000000011', 'c1000000-0000-4000-8000-000000000001', 1, 10, 'Agent update partial success', true, NULL, 'evidence.status = partial_success && evidence.command_type in ["*agent_update*"]', 'warning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'occurrence', 'job.terminal', 'natural_key', 'agent_update', 'Job requires operator attention', '{evidence.command_type} job {evidence.status}', NULL, NULL, '{"kind": "elapsed_since_trigger", "seconds": 604800}', 'job.agent_update_partial_success', 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('d1000000-0000-4000-8000-000000000012', 'c1000000-0000-4000-8000-000000000001', 1, 11, 'Agent update hard failure', true, NULL, 'evidence.status in [canceled, rejected, failed, agent_timeout, control_timeout] && evidence.command_type in ["*agent_update*"]', 'critical', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'occurrence', 'job.terminal', 'natural_key', 'agent_update', 'Job requires operator attention', '{evidence.command_type} job {evidence.status}', NULL, NULL, '{"kind": "elapsed_since_trigger", "seconds": 604800}', 'job.agent_update_hard_failure', 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('d1000000-0000-4000-8000-000000000013', 'c1000000-0000-4000-8000-000000000001', 1, 12, 'Backup request failure', true, NULL, 'evidence.status = execution_failed', 'critical', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'occurrence', 'backup.failure', 'natural_key', 'backup', 'Backup request failed', 'backup request {evidence.backup_request_id} is {evidence.status}', NULL, NULL, '{"kind": "elapsed_since_trigger", "seconds": 604800}', 'backup.request_failure', 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.policy_rules (id, group_id, rule_version, sort_order, name, enabled, traffic_selector, trigger_condition_expression, severity, created_at, updated_at, rule_kind, evidence_source, correlation_mode, category, title_template, detail_template, trigger_meta_condition, resolve_condition_expression, resolve_meta_condition, system_seed_key, armed_after_evidence_seq, armed_at) VALUES ('d1000000-0000-4000-8000-000000000014', 'c1000000-0000-4000-8000-000000000001', 1, 13, 'Capability-degraded target', true, NULL, 'evidence.status = skipped', 'warning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'occurrence', 'job.capability', 'natural_key', 'capability_degraded', 'Operation skipped because the agent lacks a required capability', '{evidence.hint}', NULL, NULL, '{"kind": "elapsed_since_trigger", "seconds": 604800}', 'job.capability_degraded', 0, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.alert_policy_lifecycle_meta (singleton, evidence_retention_days, evidence_pruned_through_seq) VALUES (true, 30, 0) ON CONFLICT DO NOTHING;

INSERT INTO public.alert_telemetry_policy_activation (singleton) VALUES (true) ON CONFLICT DO NOTHING;

INSERT INTO public.fleet_tag_settings (setting_key, value_json, updated_by, updated_at) VALUES ('order.namespace_natural_sort_enabled', 'false', NULL, CURRENT_TIMESTAMP) ON CONFLICT DO NOTHING;

INSERT INTO public.traffic_history_retention_cursors (domain, source_bucket_secs, destination_bucket_secs, updated_at) VALUES
    ('traffic_counter_samples', 0, 0, CURRENT_TIMESTAMP),
    ('traffic_counter_samples', 0, -1, CURRENT_TIMESTAMP),
    ('traffic_counter_samples', 3600, 10800, CURRENT_TIMESTAMP),
    ('traffic_counter_samples', 10800, 21600, CURRENT_TIMESTAMP),
    ('traffic_counter_samples', 21600, 86400, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;

INSERT INTO public.runtime_config_patch_generators (
    id, name, category, domain, description, field_schema, raw_generator_body, docs_metadata, built_in
)
VALUES
    (
        '55555555-5555-4555-8555-555555555555',
        'Autonomous updater enabled',
        'update',
        'agent_update',
        'Enable agent autonomous self-update from an external version manifest.',
        '{"fields":{"unmanaged_version_url":{"type":"string","default":"https://github.com/mnihyc/vpsman/releases/latest/download/version.json"},"unmanaged_interval_secs":{"type":"integer","minimum":300,"maximum":604800,"default":86400},"unmanaged_jitter_secs":{"type":"integer","minimum":0,"maximum":604800,"default":86400},"unmanaged_activate":{"type":"boolean","default":true},"unmanaged_restart_agent":{"type":"boolean","default":true}}}'::jsonb,
        $$[update]
unmanaged_enabled = true
unmanaged_version_url = {{unmanaged_version_url}}
unmanaged_interval_secs = {{unmanaged_interval_secs}}
unmanaged_jitter_secs = {{unmanaged_jitter_secs}}
unmanaged_activate = {{unmanaged_activate}}
unmanaged_restart_agent = {{unmanaged_restart_agent}}
$$,
        '{"expandable":true,"affected_sections":["update"],"patch_only":true,"predefined":true}'::jsonb,
        TRUE
    ),
    (
        '66666666-6666-4666-8666-666666666666',
        'Autonomous updater disabled',
        'update',
        'agent_update',
        'Disable agent autonomous self-update while keeping manifest URL and interval values explicit in agent config.',
        '{"fields":{"unmanaged_version_url":{"type":"string","default":"https://github.com/mnihyc/vpsman/releases/latest/download/version.json"},"unmanaged_interval_secs":{"type":"integer","minimum":300,"maximum":604800,"default":86400},"unmanaged_jitter_secs":{"type":"integer","minimum":0,"maximum":604800,"default":86400},"unmanaged_activate":{"type":"boolean","default":true},"unmanaged_restart_agent":{"type":"boolean","default":true}}}'::jsonb,
        $$[update]
unmanaged_enabled = false
unmanaged_version_url = {{unmanaged_version_url}}
unmanaged_interval_secs = {{unmanaged_interval_secs}}
unmanaged_jitter_secs = {{unmanaged_jitter_secs}}
unmanaged_activate = {{unmanaged_activate}}
unmanaged_restart_agent = {{unmanaged_restart_agent}}
$$,
        '{"expandable":true,"affected_sections":["update"],"patch_only":true,"predefined":true}'::jsonb,
        TRUE
    )
ON CONFLICT (id) DO NOTHING;
