[package]
name = "vpsman-common"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
build = "build.rs"

[dependencies]
base64.workspace = true
bytes.workspace = true
chrono.workspace = true
hex.workspace = true
hmac.workspace = true
ipnet.workspace = true
lz4_flex.workspace = true
libc.workspace = true
rand.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
snow.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
uuid.workspace = true

[[bin]]
name = "generate_frontend_contracts"
path = "src/protocol/generate_frontend_contracts.rs"

[build-dependencies]
vpsman-build-support = { path = "../../build/build-support" }
