#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export VPSMAN_DOCKER_FLEET_AGENT_COUNT="${VPSMAN_DOCKER_FLEET_AGENT_COUNT:-50}"
export VPSMAN_DOCKER_FLEET_LONG_RUNNING_SECS="${VPSMAN_DOCKER_FLEET_LONG_RUNNING_SECS:-600}"
export VPSMAN_DOCKER_FLEET_SIMULATE_API_BACKLOG="${VPSMAN_DOCKER_FLEET_SIMULATE_API_BACKLOG:-1}"
export VPSMAN_DOCKER_FLEET_EXTENDED_REVIEW="${VPSMAN_DOCKER_FLEET_EXTENDED_REVIEW:-1}"
export VPSMAN_DOCKER_FLEET_COMMAND_OUTPUT_TTL_SECS="${VPSMAN_DOCKER_FLEET_COMMAND_OUTPUT_TTL_SECS:-86400}"

"$ROOT_DIR/scripts/smoke-docker-24-agent-fleet.sh"
